[package]
name = "joshuto"
version = "0.7.0"
authors = ["Jiayi Zhao <jeff.no.zhao@gmail.com>"]
description = "Terminal file manager inspired by ranger"
homepage = "https://github.com/kamiyaa/joshuto"
license = "LGPL-3"
edition = "2018"

[dependencies]
chrono = "0.4.6"
fs_extra = "1.1.0"
lazy_static = "1.2.0"
libc = "0.2.46"
mime = "0.3.13"
mime-detective = { git = "https://github.com/cjbassi/mime-detective", branch = "arch-linux" }
open = "1.2.2"
serde = "1.0.84"
serde_derive = "1.0.84"
structopt = "0.2.14"
toml = "0.4.10"
unicode-width = "0.1.5"
whoami = "0.4.1"
xdg = "2.2.0"

# clap = "*"
# fs_extra = "*"
# lazy_static = "*"
# libc = "*"
# mime_guess = "1.8.6"
# serde = "*"
# serde_derive = "*"
# toml = "*"
# wcwidth = "*"
# whoami = "*"
# xdg = "*"

[dependencies.ncurses]
git = "https://github.com/simmons/ncurses-rs"
# version = "5.98.0"
features = [ "extended_colors", "panel", "wide" ]

[dependencies.wordexp]
version = "0.1.0"
path = "lib/wordexp-rs"

[features]
default = []
