[package]
name = "joshuto"
version = "0.9.4"
authors = ["Jiayi Zhao <jeff.no.zhao@gmail.com>"]
description = "Terminal file manager inspired by ranger"
homepage = "https://github.com/kamiyaa/joshuto"
repository = "https://github.com/kamiyaa/joshuto"
license = "LGPL-3.0"
edition = "2021"
keywords = ["tui-rs", "ranger", "file manager", "termion"]

[dependencies]
ansi-to-tui = { version = "^3", optional = true }
alphanumeric-sort = "^1"
chrono = "^0"
colors-transform = "^0"
dirs-next = "^2"
filetime = "^0"
globset = "^0"
lazy_static = "^1"
libc = "^0"
notify = "^6"
open = "^5"
phf = { version = "^0", features = ["macros"], optional = true }
rand = "^0"
# rustline latest is v12 migrate
rustyline = "^9"
serde = "^1"
serde_derive = "^1"
shell-words = "^1"
# shellexpand latest is v3 migrate
# shellexpand = { version = "^3", features = ["full"]}
shellexpand = "^2"
signal-hook = "^0"
structopt = "^0"
termion = "^2"
toml = "^0"
trash = { version = "^3", optional = true }
tui = { version = "0.21", default-features = false, features = [
  "termion",
], package = "ratatui" }
unicode-segmentation = "^1"
unicode-width = "^0"
users = "^0"
whoami = "^1"
xdg = "^2"
walkdir = "^2"

[dependencies.uuid]
version = "^1"
features = ["v4", "fast-rng", "macro-diagnostics"]

[features]
devicons = ["phf"]
file_mimetype = []
mouse = []
recycle_bin = ["trash"]
syntax_highlight = ["ansi-to-tui"]
default = ["devicons", "mouse", "recycle_bin", "syntax_highlight"]
