[package]
name = "joshuto"
version = "0.9.3"
authors = ["Jiayi Zhao <jeff.no.zhao@gmail.com>"]
description = "Terminal file manager inspired by ranger"
homepage = "https://github.com/kamiyaa/joshuto"
license = "LGPL-3.0"
edition = "2018"

[dependencies]
ansi-to-tui = { version = "^0", optional = true }
alphanumeric-sort = "^1"
chrono = "^0"
colors-transform = "^0"
dirs-next = "^2"
filetime = "^0"
globset = "^0"
lazy_static = "^1"
libc = "^0"
notify = "5.0.0-pre.15"
open = "^2"
phf = { version = "^0", features = ["macros"], optional = true }
rand = "^0"
rustyline = "^4"
serde = "^1"
serde_derive = "^1"
shell-words = "^1"
shellexpand = "^2"
signal-hook = "^0"
structopt = "^0"
termion = "^1"
toml = "^0"
trash = { version = "^1", optional = true }
tui_old = { package = "tui", version = "0.17", default-features = false, features = ["termion"] }
tui = { version = "0.18", default-features = false, features = ["termion"] }
unicode-segmentation = "^1"
unicode-width = "^0"
users = "^0"
whoami = "^1"
xdg = "^2"

[features]
devicons = [ "phf" ]
file_mimetype = []
mouse = []
recycle_bin = [ "trash" ]
syntax_highlight = [ "ansi-to-tui" ]
default = [ "devicons", "recycle_bin" ]
