[package]
name = "joshuto"
version = "0.9.1"
authors = ["Jiayi Zhao <jeff.no.zhao@gmail.com>"]
description = "Terminal file manager inspired by ranger"
homepage = "https://github.com/kamiyaa/joshuto"
license = "LGPL-3"
edition = "2018"

[dependencies]
alphanumeric-sort = "^1"
chrono = "^0"
colors-transform = "^0"
dirs-next = "^2"
filetime = "^0"
globset = "^0"
lazy_static = "^1"
libc = "^0"
open = "^1"
rand = "^0"
rustyline = "^4"
serde = "^1"
serde_derive = "^1"
shell-words = "^1"
shellexpand = "^2"
signal-hook = "^0"
structopt = "^0"
termion = "^1"
toml = "^0"
tui = "^0"
unicode-width = "^0"
users = "^0"
whoami = "^0"
xdg = "^2"
phf = { version = "^0", features = ["macros"], optional = true }
trash = { version = "^1", optional = true }
unicode-segmentation = "^1"

[features]
devicons = [ "phf" ]
file_mimetype = []
mouse = []
recycle_bin = [ "trash" ]
default = [ "devicons", "recycle_bin" ]
