# sort_type options: size, natural, basename, atime, ctime, mtime, type, random
## currently only supports: natural, mtime
tilde_in_titlebar = true

# ratios for parent view, current view and preview
column_ratio = [1, 3, 4]

# does nothing so far
scroll_offset = 6

sort_type = "natural"

[sort_option]
show_hidden = false
case_sensitive = false
reverse = false
directories_first = true

show_preview = true
