tilde_in_titlebar = true

# ratios for parent view, current view and preview
column_ratio = [1, 4, 4]

scroll_offset = 6

show_preview = true
xdg_open = false
max_preview_size = 2097152 # 2MB

# lexical, mtime, natural
sort_method = "natural"

[sort_option]
show_icons = true
show_hidden = false
case_sensitive = false
reverse = false
directories_first = true
