[[mapcommand]]
keys = [ 81 ]
command = "force_quit"

[[mapcommand]]
keys = [ 87 ]
command = "close_tab"
[[mapcommand]]
keys = [ 113 ]
command = "close_tab"

[[mapcommand]]
keys = [ 82 ]
command = "reload_dir_list"


[[mapcommand]]
keys = [ 259 ]
command = "cursor_move_up"

[[mapcommand]]
keys = [ 107 ]
command = "cursor_move_up"

[[mapcommand]]
keys = [ 258 ]
command = "cursor_move_down"

[[mapcommand]]
keys = [ 106 ]
command = "cursor_move_down"

[[mapcommand]]
keys = [ 260 ]
command = "cd"
args = [ ".." ]

[[mapcommand]]
keys = [ 104 ]
command = "cd"
args = [ ".." ]

[[mapcommand]]
keys = [ 261 ]
command = "open_file"

[[mapcommand]]
keys = [ 108 ]
command = "open_file"

[[mapcommand]]
keys = [ 10 ]
command = "open_file"


[[mapcommand]]
keys = [ 262 ]
command = "cursor_move_home"

[[mapcommand]]
keys = [ 103, 103 ]
command = "cursor_move_home"

[[mapcommand]]
keys = [ 360 ]
command = "cursor_move_end"

[[mapcommand]]
keys = [ 71 ]
command = "cursor_move_end"


[[mapcommand]]
keys = [ 338 ]
command = "cursor_move_page_down"

[[mapcommand]]
keys = [ 339 ]
command = "cursor_move_page_up"


[[mapcommand]]
keys = [ 114 ]
command = "open_file_with"


[[mapcommand]]
keys = [ 122, 104 ]
command = "toggle_hidden"


[[mapcommand]]
keys = [ 100, 100 ]
command = "cut_files"

[[mapcommand]]
keys = [ 121, 121 ]
command = "copy_files"

[[mapcommand]]
keys = [ 112, 112 ]
command = "paste_files"

[[mapcommand]]
keys = [ 112, 111 ]
command = "paste_files"
args = [ "--overwrite" ]

[[mapcommand]]
keys = [ 97 ]
command = "rename_file"
args = [ "--append" ]

[[mapcommand]]
keys = [ 65 ]
command = "rename_file"
args = [ "--prepend" ]

[[mapcommand]]
keys = [ 99, 119 ]
command = "rename_file"
args = [ "--overwrite" ]

[[mapcommand]]
keys = [ 100, 68 ]
command = "delete_files"

[[mapcommand]]
keys = [ 330 ]
command = "delete_files"


[[mapcommand]]
keys = [ 32 ]
command = "select_files"
args = [ "--toggle" ]

[[mapcommand]]
keys = [ 116 ]
command = "select_files"
args = [ "--toggle", "--all" ]

[[mapcommand]]
keys = [ 109, 107 ]
command = "console"
args = [ "mkdir " ]

[[mapcommand]]
keys = [ 59 ]
command = "console"

[[mapcommand]]
keys = [ 103, 104 ]
command = "cd"

[[mapcommand]]
keys = [ 103, 114 ]
command = "cd"
args = [ "/" ]

[[mapcommand]]
keys = [ 103, 101 ]
command = "cd"
args = [ "/etc" ]

[[mapcommand]]
keys = [ 47 ]
command = "search"

[[mapcommand]]
keys = [ 78 ]
command = "search_prev"

[[mapcommand]]
keys = [ 110 ]
command = "search_next"


[[mapcommand]]
keys = [ 20 ]
command = "new_tab"
[[mapcommand]]
keys = [ 84 ]
command = "new_tab"

[[mapcommand]]
keys = [ 23 ]
command = "close_tab"

[[mapcommand]]
keys = [ 9 ]
command = "tab_switch"
args = [ "1" ]

[[mapcommand]]
keys = [ 353 ]
command = "tab_switch"
args = [ "-1" ]

[[mapcommand]]
keys = [ 45 ]
command = "set_mode"

## Features not yet implemented

[[mapcommand]]
keys = [ 98, 98 ]
command = "bulk_rename"

