[extension]

## image formats
bmp = [
	{ command = "qimgv", fork = true, silent = true },
	{ command = "krita", fork = true, silent = true },
	{ command = "mediainfo", confirm_exit = true } ]
gif = [
	{ command = "qimgv", fork = true, silent = true },
	{ command = "krita", fork = true, silent = true },
	{ command = "mediainfo", confirm_exit = true } ]
heic = [
	{ command = "qimgv", fork = true, silent = true },
	{ command = "krita", fork = true, silent = true },
	{ command = "mediainfo", confirm_exit = true } ]
jpeg = [
	{ command = "qimgv", fork = true, silent = true },
	{ command = "krita", fork = true, silent = true },
	{ command = "mediainfo", confirm_exit = true },
jpe = [
	{ command = "qimgv", fork = true, silent = true },
	{ command = "krita", fork = true, silent = true },
	{ command = "mediainfo", confirm_exit = true },
jpg = [
	{ command = "qimgv", fork = true, silent = true },
	{ command = "krita", fork = true, silent = true },
	{ command = "mediainfo", confirm_exit = true },
pgm = [
	{ command = "qimgv", fork = true, silent = true },
	{ command = "krita", fork = true, silent = true },
	{ command = "mediainfo", confirm_exit = true },
png = [
	{ command = "qimgv", fork = true, silent = true },
	{ command = "krita", fork = true, silent = true },
	{ command = "mediainfo", confirm_exit = true },
ppm = [
	{ command = "qimgv", fork = true, silent = true },
	{ command = "krita", fork = true, silent = true },
	{ command = "mediainfo", confirm_exit = true },
svg = [
	{ command = "inkview", fork = true, silent = true },
	{ command = "inkscape", fork = true, silent = true } ]
tiff = [
	{ command = "qimgv", fork = true, silent = true },
	{ command = "krita", fork = true, silent = true } ]

## audio formats
flac = [
	{ command = "mpv", args = [ "--" ] },
	{ command = "mediainfo", confirm_exit = true } ]
m4a = [
	{ command = "mpv", args = [ "--" ] },
	{ command = "mediainfo", confirm_exit = true } ]
mp3 = [
	{ command = "mpv", args = [ "--" ] },
	{ command = "mediainfo", confirm_exit = true } ]
ogg = [
	{ command = "mpv", args = [ "--" ] },
	{ command = "mediainfo", confirm_exit = true } ]
wav = [
	{ command = "mpv", args = [ "--" ] },
	{ command = "mediainfo", confirm_exit = true } ]
ts = [
	{ command = "mpv", args = [ "--" ] , fork = true, silent = true },
	{ command = "mpv" },
	{ command = "mediainfo", confirm_exit = true } ]

## video formats
avi = [
	{ command = "mpv", args = [ "--" ] , fork = true, silent = true },
	{ command = "mediainfo", confirm_exit = true },
av1 = [
	{ command = "mpv", args = [ "--" ] , fork = true, silent = true },
	{ command = "mediainfo", confirm_exit = true },
flv = [
	{ command = "mpv", args = [ "--" ] , fork = true, silent = true },
	{ command = "mediainfo", confirm_exit = true },
mkv = [
	{ command = "mpv", args = [ "--" ] , fork = true, silent = true },
	{ command = "mediainfo", confirm_exit = true },
m4v = [
	{ command = "mpv", args = [ "--" ] , fork = true, silent = true },
	{ command = "mediainfo", confirm_exit = true },
mov = [
	{ command = "mpv", args = [ "--" ] , fork = true, silent = true },
	{ command = "mediainfo", confirm_exit = true },
mp4 = [
	{ command = "mpv", args = [ "--" ] , fork = true, silent = true },
	{ command = "mediainfo", confirm_exit = true },
webm = [
	{ command = "mpv", args = [ "--" ] , fork = true, silent = true },
	{ command = "mediainfo", confirm_exit = true },
wmv = [
	{ command = "mpv", args = [ "--" ] , fork = true, silent = true },
	{ command = "mediainfo", confirm_exit = true },

## text formats
build = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
c = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
cmake = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
conf = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
cpp = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
css = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
csv = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
cu = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
eex = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
env = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
ex = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
exs = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
go = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
h = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
hpp = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
hs = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
html = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
ini = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
java = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
js = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
json = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
kt = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
lua = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
log = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
md = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
micro = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
ninja = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
py = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
rkt = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
rs = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
scss = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
sh = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
srt = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
svelte = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
toml = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
tsx = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
txt = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
vim = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
xml = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
yaml = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
yml = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]

# archive formats
7z = [
	{ command = "7z", args = [ "x" ], confirm_exit = true },
	{ command = "file-roller", fork = true, silent = true } ]
bz2 = [
	{ command = "tar", args = [ "-xvjf" ], confirm_exit = true },
	{ command = "file-roller", fork = true, silent = true } ]
gz = [
	{ command = "tar", args = [ "-xvzf" ], confirm_exit = true },
	{ command = "file-roller", fork = true, silent = true } ]
tar = [
	{ command = "tar", args = [ "-xvf" ], confirm_exit = true },
	{ command = "file-roller", fork = true, silent = true } ]
tgz = [
	{ command = "tar", args = [ "-xvzf" ], confirm_exit = true },
	{ command = "file-roller", fork = true, silent = true } ]
rar = [
	{ command = "unrar", args = [ "e" ], confirm_exit = true },
	{ command = "file-roller", fork = true, silent = true } ]
xz = [
	{ command = "tar", args = [ "-xvJf" ], confirm_exit = true },
	{ command = "file-roller", fork = true, silent = true } ]
zip = [
	{ command = "unzip", confirm_exit = true },
	{ command = "file-roller", fork = true, silent = true } ]

# misc formats
aup = [
	{ command = "audacity", fork = true, silent = true } ]

m3u = [
	{ command = "micro" },
	{ command = "mpv" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true } ]
docx = [
	{ command = "libreoffice", fork = true, silent = true } ]
odt = [
	{ command = "libreoffice", fork = true, silent = true } ]
odf = [
	{ command = "libreoffice", fork = true, silent = true } ]
pdf = [
	{ command = "evince", fork = true, silent = true } ]

tex = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true },
	{ command = "pdflatex" } ]

torrent = [
	{ command = "transmission-gtk" } ]
