[selection]
fg = "light_yellow"
bold = true
[selection.prefix]
prefix = "  "
size = 2

[executable]
fg = "light_green"
bold = true

[regular]
fg = "white"

[directory]
fg = "light_blue"
bold = true

[link]
fg = "light_cyan"
bold = true

[socket]
fg = "light_magenta"
bold = true

[ext]

[ext.bmp]
fg = "yellow"
[ext.jpg]
fg = "yellow"
[ext.jpeg]
fg = "yellow"
[ext.png]
fg = "yellow"
[ext.ppm]
fg = "yellow"
[ext.svg]
fg = "yellow"
[ext.gif]
fg = "yellow"

[ext.wav]
fg = "magenta"
[ext.flac]
fg = "magenta"
[ext.mp3]
fg = "magenta"
[ext.avi]
fg = "magenta"
[ext.m3u]
fg = "magenta"
[ext.mov]
fg = "magenta"
[ext.mp4]
fg = "magenta"
[ext.mkv]
fg = "magenta"
[ext.m4a]
fg = "magenta"
[ext.ts]
fg = "magenta"
[ext.webm]
fg = "magenta"
[ext.wmv]
fg = "magenta"

[ext.7z]
fg = "red"
[ext.zip]
fg = "red"
[ext.bz2]
fg = "red"
[ext.gz]
fg = "red"
[ext.tar]
fg = "red"
[ext.tgz]
fg = "red"
[ext.xz]
fg = "red"
[ext.rar]
fg = "red"
